@startuml ClassDiagramUS1+2
'Alt+D = preview


class Main{
'BoardGameApp
}

package Entities{

    class Application{
        -Library library
        -User user
        'Getters and setters'
    }

    class Library{
        -Game game
        -search(Game game) 'Maybe String input for gameName'
        -showAllGames()
        '-filter(Enum genre)
        -filterNOOfPlayers(int minNOOfPlayers, int maxNOOfPlayers)
        -filterAge(int minAgeOfPlayers)'
    }

    class User{
        -String userName
        -Integer userId
        -String email
        -String password
        -MyCollection myCollection
        'Getters and setters'
    }

    class MyCollection{
        -String listName
        -Integer listId
        -List <Game> games
        'Det er listen der bruger funktionerne, spillet bliver bare sendt med rundt.'
        -addGame(Integer gameId, Integer listId)
        -removeGame(Integer gameId, Integer listId)
    } 

    class Game {
        -String title
        -Integer gameId
        -String description
        -int minNOOfPlayers
        -int maxNOOfPlayers
        -int minAge
        -int maxAge
        -int releaseYear
        -List <String> languages
        -Genre genre
        'Getters and setters'
    }

    enum Genre{
    }
}

'Vi har ikke fokus på persistence og controllers i denne iteration, hvorfor vi bare har de to packages med, men ikke har udviklet dem
package Controllers{
    class LibraryController{
        addRoutes()
    }

    class UserController{
        addRoutes()
    }

    class GameController{
        addRoutes()
    }

    class MyCollectionsController{
        addRoutes()
    }

}

package Persistence{
    class LibraryMapper{}

    class UserMapper{}

    class GameMapper{}

    class MyCollectionMapper{}

}

'Relations
'Entities
Main -- Application
Application --* Library
Application --o User
User --* MyCollection
MyCollection --o Game
Library --* Game
Game --* Genre


@enduml

implements ..|>
extends <|-- (is-a)
composition *-- (must-have)
Aggregation o-- (can-have)
Associering <-- (knows-of)
Dependency ..> (uses)